### ISSUE TITLE
Object error

### ISSUE THREAD

**Issue by drdah123** [sahandghavidel/twitter#1]
hello,
this is appear to me and i do not why
<img width="649" alt="object" src="https://user-images.githubusercontent.com/108929184/185734391-a9bfae6c-e097-411f-b124-91d9cda11fff.png">
[zip.zip](https://github.com/sahandghavidel/twitter/files/9386445/zip.zip)

**Comment by sahandghavidel** [comment]
Hi, check your google client id and secret in your env file. Others seem to be ok
